orbs: 
    python: circleci/python@2.0.1
version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          command: |
            pip install requests
            pip install pytest
            pytest --junitxml=test-results/junit.xml Testmain.py
      - store_test_results:
          path: test-results

workflows:
  testing-gitapi:
    jobs:
      - build-and-test       
